### ISSUE TITLE
Error using library react-native-call-detection

### ISSUE THREAD

**Issue by hostcia** [priteshrnandgaonkar/react-native-call-detection#61]
I am trying to use the react-native-call-detection library to get the incoming call number.

But when I start the android emulator this low error appears.

I have already run react-native unlink react-native-call-detection, but the error continues. Having identify the other mistakes but to no avail!

If I completely remove react-native-call-detection then the emulator opens without any error.

Can someone help me please?

Thanks.

````
Microsoft Windows [versão 10.0.18363.535]
(c) 2019 Microsoft Corporation. Todos os direitos reservados.

L:\wAPP\reactCall>react-native run-android
error React Native CLI uses autolinking for native dependencies, but the following modules are linked manually: 
  - react-native-call-detection (to unlink run: "react-native unlink react-native-call-detection")
This is likely happening when upgrading React Native from below 0.60 to 0.60 or above. Going forward, you can unlink this dependency via "react-native unlink <dependency>" and it will be included in your app automatically. If a library isn't compatible with autolinking, disregard this message and notify the library maintainers.
Read more about autolinking: https://github.com/react-native-community/cli/blob/master/docs/autolinking.md
info Running jetifier to migrate libraries to AndroidX. You can disable it using "--no-jetifier" flag.
Jetifier found 1645 file(s) to forward-jetify. Using 8 workers...
info JS server already running.
info Installing the app...

> Task :app:processDebugManifest FAILED

See http://g.co/androidstudio/manifest-merger for more information about the manifest merger.


Deprecated Gradle features were used in this build, making it incompatible with Gradle 6.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/5.5/userguide/command_line_interface.html#sec:command_line_warnings
21 actionable tasks: 3 executed, 18 up-to-date
L:\wAPP\reactCall\android\app\src\debug\AndroidManifest.xml:11:7-34 Error:
        Attribute application@allowBackup value=(false) from AndroidManifest.xml:11:7-34
        is also present at [:react-native-call-detection] AndroidManifest.xml:14:9-35 value=(true).
        Suggestion: add 'tools:replace="android:allowBackup"' to <application> element at AndroidManifest.xml:7:5-117 to override.

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:processDebugManifest'.
> Manifest merger failed : Attribute application@allowBackup value=(false) from AndroidManifest.xml:11:7-34
        is also present at [:react-native-call-detection] AndroidManifest.xml:14:9-35 value=(true).
        Suggestion: add 'tools:replace="android:allowBackup"' to <application> element at AndroidManifest.xml:7:5-117 to override.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 7s

error Failed to install the app. Make sure you have the Android development environment set up: https://facebook.github.io/react-native/docs/getting-started.html#android-development-environment. Run CLI with --verbose flag for more details.      
Error: Command failed: gradlew.bat app:installDebug -PreactNativeDevServerPort=8081
L:\wAPP\reactCall\android\app\src\debug\AndroidManifest.xml:11:7-34 Error:
        Attribute application@allowBackup value=(false) from AndroidManifest.xml:11:7-34
        is also present at [:react-native-call-detection] AndroidManifest.xml:14:9-35 value=(true).
        Suggestion: add 'tools:replace="android:allowBackup"' to <application> element at AndroidManifest.xml:7:5-117 to override.

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:processDebugManifest'.
> Manifest merger failed : Attribute application@allowBackup value=(false) from AndroidManifest.xml:11:7-34
        is also present at [:react-native-call-detection] AndroidManifest.xml:14:9-35 value=(true).
        Suggestion: add 'tools:replace="android:allowBackup"' to <application> element at AndroidManifest.xml:7:5-117 to override.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 7s

    at checkExecSyncError (child_process.js:610:11)
    at execFileSync (child_process.js:628:15)
    at runOnAllDevices (L:\wAPP\reactCall\node_modules\@react-native-community\cli-platform-android\build\commands\runAndroid\runOnAllDevices.js:94:39)
    at buildAndRun (L:\wAPP\reactCall\node_modules\@react-native-community\cli-platform-android\build\commands\runAndroid\index.js:158:41)
    at L:\wAPP\reactCall\node_modules\@react-native-community\cli-platform-android\build\commands\runAndroid\index.js:125:12
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async Command.handleAction (L:\wAPP\reactCall\node_modules\@react-native-community\cli\build\index.js:164:9)        

L:\wAPP\reactCall>  
````

**Comment by appy9** [comment]
I added this attribute in application tag
`tools:replace="android:allowBackup"` and it worked.

**Comment by priteshrnandgaonkar** [comment]
Reopen it if the it still persists.
